name: Linx Tests

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run bu command
        default: node runner.js

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
        
      - name: Run
        uses: joonvena/robotframework-docker-action@v1.1
        with:
          robot_tests_dir: test
      - name: reports folder
        uses: actions/upload-artifact@v4.3.1
        if: always()
        with: 
          name: reports
          path: reports

  report:
    if: always()
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
      - name: Download report
        uses: actions/download-artifact@v4.1.4
        with:
          name: reports
      - name: Output
        uses: joonvena/robotframework-docker-action@v1.1
        with: ${{ secrets.ROBOT }}
        
          
          
